import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./fonts.css"
import { Providers } from '@/app/providers'
import { Container } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container">
          <Providers>
          <Container maxW="100vw" maxH="100vh" overflow="hidden">
            {children}
          </Container>
          </Providers>
      </body>
    </html>
  );
}
